# Generated by Django 4.0.3 on 2022-03-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='歌名')),
                ('autuor', models.CharField(max_length=40, verbose_name='歌手')),
                ('total_time', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='总时长')),
                ('issue_date', models.DateField(verbose_name='发行时间')),
                ('album_name', models.CharField(max_length=50, verbose_name='专辑名称')),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
                'db_table': 'music',
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11, verbose_name='姓名')),
                ('sex', models.CharField(max_length=11, verbose_name='性别')),
                ('age', models.IntegerField(default=1, verbose_name='年龄')),
                ('nationality', models.CharField(max_length=11, verbose_name='国籍')),
                ('date_of_birth', models.DateField(verbose_name='出生日期')),
            ],
            options={
                'verbose_name': '歌手',
                'verbose_name_plural': '歌手',
                'db_table': 'singer',
            },
        ),
    ]
