# Generated by Django 4.0.3 on 2022-03-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='total_time',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='总时长'),
        ),
    ]
