# Generated by Django 4.0.3 on 2022-03-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_book_market_prices_book_pub_alter_author_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者', 'verbose_name_plural': '作者'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '图书', 'verbose_name_plural': '图书'},
        ),
    ]
